### ISSUE TITLE
Select some shapes or symbols but, a shape (Rect) is selected.

### ISSUE THREAD

**Issue by thierryc** [tristandenyer/sketch-plugin-lorem-picsum#3]
Sketch 52.2 Select some shapes or symbols but, a shape (Rect) is selected.

Interesting plugin. Thanks to share it. 

<img width="582" alt="image" src="https://user-images.githubusercontent.com/197471/47444976-be696300-d785-11e8-98f2-e29f91efa1f6.png">

**Comment by tristandenyer** [comment]
You are correct. I retested this in the latest Sketch and it _does NOT_ work. I tested it in version 51, and it _does_ work. I will be working on an update for this. Thanks for letting me know!

**Comment by tristandenyer** [comment]
@thierryc Thank you again for letting me know of this issue. I have updated the plugin to 0.1.1, and tested that it works in Sketch 52.2. Feel free to [download the latest release](https://github.com/tristandenyer/sketch-plugin-lorem-picsum/releases/tag/v0.1.1-beta).

**Comment by thierryc** [comment]
Works 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/197471/47497169-16a47180-d827-11e8-9fef-13e70ab29ffc.png">

Thank you @tristandenyer
